const women=['Sarees','Kurtis','Churidars','Salwar Suits','Anarkali Dresses','Gowns','Tops','Leggings','Nightwear','Casual Wear','Party Wear','Ethnic Wear'];
const girls=['Frocks','Party Frocks','Traditional Dresses','Lehenga Choli','Pattu Pavadai','Gowns','Tops & Bottom Sets','Casual Dresses','Festive Dresses'];
const products=[
 {name:'Kanjivaram Bloom Saree',cat:'Women',type:'Sarees',sizes:'Free Size',old:1899,price:1399,tag:'Best Seller',img:'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=82'},
 {name:'Meher Floral Anarkali',cat:'Women',type:'Anarkali Dresses',sizes:'S, M, L, XL, XXL',old:1699,price:1199,tag:'New Arrivals',img:'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=800&q=82'},
 {name:'Aarna Festive Lehenga',cat:'Girls',type:'Lehenga Choli',sizes:'2–12 Years',old:1499,price:999,tag:'Festival',img:'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=800&q=82'},
 {name:'Noor Embroidered Kurti',cat:'Women',type:'Kurtis',sizes:'M, L, XL, XXL',old:1099,price:749,tag:'Trending',img:'https://images.unsplash.com/photo-1583391733981-8498408ee587?auto=format&fit=crop&w=800&q=82'},
 {name:'Mithra Party Frock',cat:'Girls',type:'Party Frocks',sizes:'2–10 Years',old:1299,price:899,tag:'Offer',img:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=82'},
 {name:'Vanya Ethnic Salwar Set',cat:'Women',type:'Salwar Suits',sizes:'S, M, L, XL',old:1599,price:1099,tag:'Best Seller',img:'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=82'},
 {name:'Nila Pattu Pavadai',cat:'Girls',type:'Pattu Pavadai',sizes:'1–10 Years',old:1799,price:1299,tag:'Festival',img:'https://images.unsplash.com/photo-1610189012906-4c0aa9b9781e?auto=format&fit=crop&w=800&q=82'},
 {name:'Ira Evening Gown',cat:'Women',type:'Gowns',sizes:'S, M, L, XL',old:1999,price:1499,tag:'New Arrivals',img:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=82'}
];
const wa=(product='this dress')=>`https://wa.me/919876543211?text=${encodeURIComponent(`Hi JMS Textiles, I am interested in ${product}. Please share availability, sizes and ordering details.`)}`;
document.querySelectorAll('[data-wa]').forEach(a=>{a.href=wa(a.dataset.wa==='general'?'a dress from your collection':a.dataset.wa);a.target='_blank';a.rel='noopener'});
document.querySelectorAll('.chips').forEach((box)=>{const list=box.dataset.group==='Women'?women:girls;box.innerHTML=list.map(x=>`<button onclick="renderProducts('${box.dataset.group}','${x.replaceAll("'","\\'")}');document.querySelector('#collection').scrollIntoView()">${x}</button>`).join('')});
function renderProducts(cat='All',type=''){let list=products.filter(p=>(cat==='All'||p.cat===cat)&&(!type||p.type===type));if(!list.length)list=products.filter(p=>p.cat===cat);document.querySelector('#productGrid').innerHTML=list.map((p,i)=>`<article class="product-card"><div class="product-image" style="background-image:url('${p.img}')"><span class="tag">${p.tag}</span></div><div class="product-info"><span class="meta">${p.cat} · ${p.type}</span><h3>${p.name}</h3><span class="sizes">Sizes: ${p.sizes}</span><div class="price"><span class="original">₹${p.old}</span><span class="offer">₹${p.price}</span></div><div class="card-actions"><button onclick="showProduct('${p.name}')">View Details</button><a target="_blank" rel="noopener" href="${wa(p.name)}">Order on WhatsApp</a></div></div></article>`).join('')}
document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-cat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.cat)});
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelector('#collection').scrollIntoView();const tag=b.dataset.filter;const found=products.filter(p=>p.tag===tag);document.querySelector('#productGrid').innerHTML=found.map(p=>`<article class="product-card"><div class="product-image" style="background-image:url('${p.img}')"><span class="tag">${p.tag}</span></div><div class="product-info"><span class="meta">${p.cat} · ${p.type}</span><h3>${p.name}</h3><span class="sizes">Sizes: ${p.sizes}</span><div class="price"><span class="original">₹${p.old}</span><span class="offer">₹${p.price}</span></div><div class="card-actions"><button onclick="showProduct('${p.name}')">View Details</button><a target="_blank" href="${wa(p.name)}">Order on WhatsApp</a></div></div></article>`).join('')});
function showProduct(name){const p=products.find(x=>x.name===name);document.querySelector('#dialogBody').innerHTML=`<div class="dialog-content"><img src="${p.img}" alt="${p.name}"><div class="dialog-copy"><p class="eyebrow">${p.tag}</p><h2>${p.name}</h2><p>${p.cat} · ${p.type}</p><p>Available sizes: <strong>${p.sizes}</strong></p><div class="price"><span class="original">₹${p.old}</span><span class="offer">₹${p.price}</span></div><p>Message us for colour options, availability and delivery details.</p><a class="btn dark" target="_blank" href="${wa(p.name)}">Order on WhatsApp</a></div></div>`;document.querySelector('#productDialog').showModal()}
renderProducts();
